ls:
  src:
    types:
      .ts: regex:^[a-z]+\.type\.ts$
    .js: kebab-case
    .jsx: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .astro: kebab-case | kebab-case | regex:\[[A-Za-z]+\]

ignore:
  - src/env.d.ts
  - node_modules
  - .vscode
  - .husky
  - .git
  - public
  - .astro
  - .vercel
