ls:
  src:
    .js: kebab-case
    .jsx: kebab-case
    .ts: kebab-case
    .tsx: kebab-case
    .astro: kebab-case | kebab-case

ignore:
  - src/env.d.ts
  - node_modules
  - .vscode
  - .husky
  - .git
  - public/
