media: public
content:
  - name: business
    label: Business Config
    path: business.json
    type: file
    icon: building
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
        options:
          maxLenght: 170
      - name: site
        label: URL Website
        description: "Example: https://elevenestudio.com"
        type: string
        required: true
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: robots
        label: Robots
        type: object
        hidden: true
        fields:
          - name: index
            label: No Index
            type: boolean
            default: false
          - name: follow
            label: No Follow
            type: boolean
            default: false
      - name: openGraph
        label: Open Graph
        description: Image size must be 1200 x 630 px and must weigh less than 1M
        required: true
        type: image
        options:
          path: public/
          input: public/
          output: /
          extensions: [ jpg, jpeg, png ]
      - name: contact
        label: Contact
        type: object
        fields:
          - name: tel
            label: Phone
            type: object
            fields:
              - name: ext
                description: "Example: 502"
                label: Extension
                type: number
                required: true
                default: 502
              - name: number
                label: Number
                type: number
                required: true
          - name: whatsapp
            label: WhatsApp
            type: object
            fields:
              - name: ext
                description: "Example: 502"
                label: Extension
                type: number
                required: false
                default: 502
              - name: number
                label: Number
                type: number
                required: false
          - name: email
            label: Email
            type: string
            required: true
            pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$
      - name: address
        label: Address
        type: object
        fields:
          - name: location
            label: Location
            type: string
            required: true
      - name: googleTagManager
        label: Google Tag Manager
        type: object
        fields:
          - name: id
            label: ID
            type: string
      - name: social
        label: Social Media
        type: object
        fields:
          - name: facebook
            label: Facebook
            type: string
          - name: instagram
            label: Instagram
            type: string
          - name: tiktok
            label: TikTok
            type: string
          - name: youtube
            label: YouTube
            type: string
          - name: linkedin
            label: LinkedIn
            type: string
          - name: twitter
            label: Twitter
            type: string
      - name: configuracion
        label: Configuración
        type: object
        fields:
          - name: emailSender
            label: Remitente del correo (Email Sender)
            type: string
            required: false
            pattern: ^[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}$
          - name: bccEmail
            label: Correos en copia oculta (BCC)
            type: array
            items:
              type: string
              pattern: ^[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}$
            required: false
          - name: resendToCompany
            label: Reenviar a la empresa
            description: "Si es verdadero, el correo también será enviado a la dirección de correo de la empresa"
            type: boolean
            default: true

      